workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: 3.24.3
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_IDENTIFIER: "com.aligorithm.istanbulNavigasyon"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS Release IPA
        script: |
          flutter build ipa --release --build-name=2.0.0 --build-number=63
    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/bundle/release/*.aab
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true