workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: 3.24.3
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_IDENTIFIER: "com.aligorithm.istanbulNavigasyon"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS Release IPA
        script: |
          flutter build ipa --release --build-name=2.0.0 --build-number=59
    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/bundle/release/*.aab
    publishing:
      app_store_connect:
        api_key: "729WXR2HQV"
        key_id: "2HT9RK6864"
        issuer_id: "392f0cdf-666f-4e72-9869-83b25e0c5e08"
        submit_to_testflight: true